Language: EN
# Shows if there is available new version on login with tryme.versioncheck permission node
ShowNewVersion: false
Cheats:
  # Defines how long (in seconds) it should pass after question was given for correct answer to count
  # This can help to minimize cheater amount by creating auto answering bots
  minAnswerTime: 0
  # Do you want to count answer as correct and proceed with rewards if he answered too fast
  CountAsCorrect: true
  CommandsToPerform:
  - msg [playerName] You answered too quickly, using cheats?!
# Do you want Quiz to start with server
EnableOnStartup: true
# Defines what command will be performed when server/plugin starts
# This works only when EnableOnStartup is enabled
CommandToPerform: tryme amode
# Players needed to start scheduled quiz game
MinPlayersToRun: 2
# Do you want to stop manualy started quiz if there is not enough players
StopManualMode: false
# Where do you want to print out question: chatbox, actionbar
QuestionPlace: chatbox
# How long in seconds should we show question inside actionbar. Set this to 0 if you want to show question until someone answers or answer time ends
ActionBarTimer: 30
Modes:
  # Question/answer mode
  QMODE:
    # Do you want to ignore spaces in answers
    IgnoreSpaces: true
    # Interval between questions/tasks in seconds
    Interval: 800
    # Time limit for answer/task
    # This should be be higher than interval between questions/tasks
    TimeForAnswer: 600
  # Flash mode. First to type in showen word
  FMODE:
    IgnoreSpaces: true
    Interval: 800
    TimeForAnswer: 600
    # Do you want to ignore capitalization when answering into flash mode question
    IgnoreCaps: true
  # Math mode. Solve equation
  MMODE:
    IgnoreSpaces: true
    Interval: 800
    TimeForAnswer: 600
  # Decode mode. Figure out meaning of encoded word
  DMODE:
    IgnoreSpaces: true
    Interval: 800
    TimeForAnswer: 600
  # Custom mode. Custom questions and commands
  CMODE:
    IgnoreSpaces: true
    Interval: 800
    TimeForAnswer: 600
  # HangMan mode. Guess word by one letter at the time
  HMODE:
    IgnoreSpaces: true
    Interval: 800
    TimeForAnswer: 600
    # Amount in percentage we want to hide of each word
    # This is only a percentage change in hiding each letter, which means that in some situations you could get all letters hidden and in some rare only one
    # At least two letters will be hidden
    HideAmount: 80
    # When set to false we will not hide spaces if word has any, for example `Ha_ Ba__` as of `Hay Bale`
    # When set to true we will now show spaces, for example `Ha__Ba__` as of `Hay Bale`
    HideSpaces: false
    # When set to true players will have option to try and guess one of the letters
    # If player gets correct one then it will be shown
    # If only one letter is missing then player can ether guess word or last letter to get reward
    AllowLetterGuessing: true
    # Time in seconds between letter guesing, this will not apply for guessing correct word but only for a letter
    GuessDelay: 5
  # Kill mode. Kill defined entity
  KMODE:
    IgnoreSpaces: true
    Interval: 800
    TimeForAnswer: 600
  # All mode. Includes multiple game modes
  AMODE:
    IgnoreSpaces: true
    Interval: 800
    TimeForAnswer: 600
    # Which game modes you want to include into amode
    IncludedModes:
      Qmode: true
      Fmode: false
      Mmode: false
      Dmode: false
      Cmode: false
      Hmode: false
      Emode: false
      Bmode: false
      Pmode: false
      Kmode: false
  # Eat mode. Consume specific item
  EMODE:
    Interval: 800
    TimeForAnswer: 600
  # Brake mode. Brake specific blocks
  BMODE:
    Interval: 800
    TimeForAnswer: 600
  # Place mode. Place specific blocks
  PMODE:
    Interval: 800
    TimeForAnswer: 600
# Do you want to show questions in console
ShowInConsole: false
# Broadcasts answer after answer time ends
ShowAnswer: true
# Do you want to use sheduler for your server
UseScheduler: false
# How often to check for schedule in seconds. Keep it at 60 sec if you dont care about seconds :)
SchedulerInterval: 300
# You need to enable this one to use so caled Daily rewards for best quiz game players
DailyScheduler: false
# Do you want to use option to answer just by typing into chat
UseChatAnswer: true
# Do you want to use commands to answer into questions (no spam into chat)
UseCommandAnswer: false
# Do you want to use random fireworks after correct answer
UseFireworks: false
# When this set to true, left time will be shown in action bar for each player
ShowLeftTime: false
# List of seconds when to show left time for players
ShowLeftTimeList:
- 10
- 5
- 4
- 3
- 2
- 1
DataBase:
  # Do you want to use Mysql database system or SQLite
  # Use: mysql or sqlite
  DataBaseType: mysql
  # Not usable if sqlite file system chosen
  # Usually localhost or 127.0.0.1
  mysqlHost: cali.bloom.host
  # Default port is 3306
  mysqlPort: 3306
  # Database table name
  mysqlDatabase: s1723_TryMe
  # Prefix for each table
  mysqlDatabasePrefix: s1723_TryMe
  # Database username, usually its root
  mysqlUsername: u1723_xVCqLwpX2s
  # Your mysql database password, keep it as strong as posible
  mysqlPassword: bd@.cRaAF1J2ZuMKj0vgF!hI
Chat:
  # Do you want to show players original message into chat
  ShowChatAnswer: true
  # Do you want o to broadcast custom message with correct answer
  BroadcastCorrectAnswer: true
  # If you have issue when creating questions it to be shown in chat, change this and try again
  UseLowPriority: true
  # List of worlds where plugin will not show questions and will not check for correct answers
  DisabledWorlds:
  - WorldSome
  - WorldAnother
Titles:
  # Do you want to show Title
  ShowTitle: false
  # Do you want to Show SubTitle
  ShowSubtitle: false
  # Do you want to Show ActionBar
  ShowActionBar: false
Compatibility:
  # Do you want to ignore answers from McMMO party and admin chat
  mcMMO: true
  # Do you want to ignore answers from faction chat except public chat
  Faction: true
  HeroChat:
    # Do you want to enable support for HeroChat chanels
    Use: false
    # Chanel name to use for broadcasting messages and get answers
    ChanelName: Global
